### ISSUE TITLE
Задача

### ISSUE THREAD

**Issue by AlexGaidukov** [AlexGaidukov/gipertest_streaming#1]
Суть такова:
Есть редактор тестов -  у него есть функция вставки видео, там просто подаётся видеофайл, который загружается в файл учебника. Он проигрывается через SWF плеер uppod.
Новая версия этого uppod поддерживает youtube и rtmp ссылки. Сейчас я пушнул новую версию этого плеера в ветку _New_uppod_.
Нужно добавить в гуй рядом с имеющейся кнопкой видео добавить кнопку с таким функционалом.
- При нажатии на неё открывается окно с:
  - Тектовым полем для ввода ссылки
  - Кнопками Ок и Отмена
- При нажатии Отмены окно очевидно закрывается
- При нажатии на Ок:
  - Если ссылки нет, то алерт.
  - Если ссылка есть, то в открытое место в учебнике (где стоит курсор) добавляется эта ссылка вместе с кодом, который позволит посмотреть видео по ссылке.
    Валидность ссылок проверять не надо.

**Comment by framebassman** [comment]
Fixed.
